apiVersion: v1
kind: Service
metadata:
  name: banking-app-svc
  labels:
    app: banking-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "5000"
spec:
  selector:
    app: banking-app
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: ClusterIP
