apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-app
  labels:
    app: banking-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-app
  template:
    metadata:
      labels:
        app: banking-app
        version: IMAGE_PLACEHOLDER  # new label showing deployed version
    spec:
      containers:
      - name: banking-app
        image: IMAGE_PLACEHOLDER   # Jenkins will replace this dynamically
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5

