apiVersion: v1
kind: Service
metadata:
  name: banking-app-svc
spec:
  selector:
    app: banking-app
  ports:
    - protocol: TCP
      port: 80          # external port
      targetPort: 5000  # container port
  type: NodePort       # exposes app outside the cluster

